### ISSUE TITLE
Error in console when disabling DuelMe

### ISSUE THREAD

**Issue by WolfMaster333** [teozfrank/DuelMe#46] opened 2016-01-10 15:17 UTC
[17:49:19 INFO]: [DuelMe] [Info] Disabling.
[17:49:19 ERROR]: Error occurred while disabling DuelMe v0.9.17.0 (Is it up to date?)
java.lang.NullPointerException
        at com.teozcommunity.teozfrank.duelme.util.FileManager.saveDuelArenas(FileManager.java:232) ~[?:?]
        at com.teozcommunity.teozfrank.duelme.main.DuelMe.onDisable(DuelMe.java:132) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:323) ~[craftbukkit-1.5.2-R1.1-current.jar:git-PaperSpigot-9172103-07c3001]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:356) [craftbukkit-1.5.2-R1.1-current.jar:git-PaperSpigot-9172103-07c3001]
        at us.Myles.PWP.TransparentListeners.PerWorldPluginLoader.disablePlugin(PerWorldPluginLoader.java:140) [PerWorldPlugins.jar:?]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:423) [craftbukkit-1.5.2-R1.1-current.jar:git-PaperSpigot-9172103-07c3001]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:416) [craftbukkit-1.5.2-R1.1-current.jar:git-PaperSpigot-9172103-07c3001]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.disablePlugins(CraftServer.java:337) [craftbukkit-1.5.2-R1.1-current.jar:git-PaperSpigot-9172103-07c3001]
        at net.minecraft.server.v1_8_R3.MinecraftServer.stop(MinecraftServer.java:456) [craftbukkit-1.5.2-R1.1-current.jar:git-PaperSpigot-9172103-07c3001]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:652) [craftbukkit-1.5.2-R1.1-current.jar:git-PaperSpigot-9172103-07c3001]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]

**Comment by teozfrank** [comment] 2016-01-10 16:37
I dont support paperspigot. Also you must be using at least minecraft version 1.8.8 nothing lower.

**Comment by vst8800** [comment] 2016-01-12 17:00
Many servers use PaperSpigot as it allow more people with less lag on same hardware. Also you look at how the jar file is named however we are using latest PaperSpigot 1.8.8. It will be highly appreciated if you could look at this instead of just ignoring which prevents us from using your plugin.

**Comment by teozfrank** [comment] 2016-01-12 18:45
Regardless of how many people use PaperSpigot, its at my own discretion if I wish to support it or not. Yes you are correct it was the jar name that put me off my apologies. But I require more information on how this error is produced not just the error itself. I need steps on how its reproduced so I can test it myself. Thanks.

**Comment by vst8800** [comment] 2016-01-12 19:54
Hi thanks for your answer. You can reproduce it by just stopping the server with ./stop command ingame or in Console (for PaperSpigot 1.8.8). If you wish I can test with Spigot 1.8.8 too as we have a test server.

**Comment by vst8800** [comment] 2016-01-16 00:33
No respomse - so thank you for loosing our time. Good luck with the not working plugin we already moved to another with more helpful dev.

**Comment by teozfrank** [comment] 2016-01-16 02:03
Please try it with spigot 1.8.8 and tell me does it still happen. Your response above is very childish, if you wish to move to another plugin then go right ahead but there is no need to rub it in my face.

**Comment by vst8800** [comment] 2016-01-16 15:31
Hi, Tested. Same results on Spigot 1.8.8:

http://pastebin.com/ky3nczUN

**Comment by teozfrank** [comment] 2016-01-16 22:51
could you please attach your config.yml, duelarenas.yml, messages.yml and signs.yml please so I can try and reproduce.

**Comment by gogobebe2** [comment] 2016-01-17 01:06
@vst8800 Fucking idiot. @teozfrank is is giving his service to the community by making "Duel Me" for fun and was kind enough to put it out there for free so others can use it. Then you come along and get all demanding and act as though it's his responsibility to fulfill your special needs.

**Comment by WolfMaster333** [comment] 2016-01-21 20:51
gogobebe this plugin is suck pls remove on spigot !

**Comment by gogobebe2** [comment] 2016-01-21 21:38
@WolfMaster333 ? wot ?

**Comment by teozfrank** [comment] 2016-01-22 14:01
@WolfMaster333 I think we should remove you from spigot! xD

@vst8800 will check it out this weekend when I get time, thanks for reporting back. :)

**Comment by WolfMaster333** [comment] 2016-01-22 18:17
phah this plugin is suck man this is the truth

**Comment by teozfrank** [comment] 2016-01-22 19:02
Why is it?

**Comment by teozfrank** [comment] 2016-02-02 21:05
Closed as requested information was not provided, Also I cannot reproduce this error locally. If you can provide the requested details please reopen an issue and provide them. Thanks.

**Closed by teozfrank** 2016-02-02 21:05 UTC
Labels: bug
