### ISSUE TITLE
A few issues I found

### ISSUE THREAD

**Issue by rocky143** [teozfrank/DuelMe#26] opened 2015-08-04 15:34 UTC
After creating arenas, I found Yaw/Pitch was not saved to the arena file.
Not that its a big issue but it would be great if this can be fixed.

Here is the current duelarenas.yml https://i.gyazo.com/2790f6f3dce68bc11e73dbb54b095d83.png

Edit: Also, I found a few other issues.
1. When blocked command typed, you get 2 same messages:
http://i.imgur.com/6UDhZSE.png
2. When invite a player, the invited player receives a message to accept + opens gui. Could the message be disabled?
http://i.imgur.com/z4fqfQQ.png
3. Inventory click error. Happens when a requested player clicks anywhere outside inventory:
http://pastebin.com/XAUezGFn

Thanks in advanced!

**Comment by teozfrank** [comment] 2015-08-04 20:45
- After creating arenas, I found Yaw/Pitch was not saved to the arena file.
Its not meant to be saved to the file.

1.This should be fixed.
2. This is also fixed will send the message OR open the gui menu depending on the settings in config.yml
3. This should also be fixed.

Checkout the latest update in spigot to check if these problems are gone, besides the yaw / pitch as its intentional, not a bug. Will be uploaded in a few mins.

**Comment by rocky143** [comment] 2015-08-05 01:58
Thank you very much for the quick fixes. You have done a great job. I have sent you a little donation and will donate more in the future when possible.

For Yaw and Pitch. Since its not saved to the file, when the server restarts and player joins the arena, they only face to Yaw: 0.0 and Pitch: 0.0. In some cases, the would face the area walls.
Its nothing urgent but if you ever have some spare time. As a request, please add the saving of it.

Really appreciate you effort on your amazing plugin!

**Comment by teozfrank** [comment] 2015-08-07 17:06
Thank you for your donation, I will add that when I get the time to do so. I will look at the messages too again when I get the time. Thanks.

**Comment by teozfrank** [comment] 2015-08-19 14:12
Yaw and Pitch have been added in the latest update, you will need to set your spawnpoints on each arena to see the effect.

**Closed** 2015-10-01 01:06 UTC
Labels: bug
