### ISSUE TITLE
Bugs I Found/Suggestions

### ISSUE THREAD

**Issue by Walnert** [teozfrank/DuelMe#31] opened 2015-09-01 02:25 UTC
1.When the duel starts, it doesn't heal and feed you, but when it ends, it takes away the food bars you get from eating steak (I added that to the kit).

2.Once it spawned both participants in the same spawnpoint.

3. (Suggestion) I suggest simply typing /duel to send and accept duels. So if two people want to duel and it isn't clear who is sending and who is accepting, they can just both type "/duel {Other person's Name}" and start right away.

This is the best simple duel plugin I've found, so it would mean a lot to me for you to fix these issues.

Thanks!

**Comment by Walnert** [comment] 2015-09-01 02:31
That's weird. GitHub isn't letting me have a "3." It just turns it into an indented "1." Well anyway, interpret that as a "3."

**Comment by xion87** [comment] 2015-09-06 18:07
i confirm this, teleport on same spawn is stillll present or in different arena...

**Comment by teozfrank** [comment] 2015-09-08 10:58
1. it restores your health and hunger before the duel. I snould give you full health / hunger I will look into this.
2. Does this always occur or is it random.
3. That wont work with the current system I have implemented. What I could do is add a command that would list the requests the player currently has.

**Comment by Walnert** [comment] 2015-09-08 23:37
1. It consistently doesn't heal and feed anyone when they join a duel. Something I didn't tell you is that I made a custom kit that has iron armor, an iron sword, a bow and 24 arrows, and--this might be important--24 steak.
2. It's seemingly random

**Comment by xion87** [comment] 2015-09-09 23:30
fix these damn bugs, are starting to getting old now.... >.<

**Comment by gogobebe2** [comment] 2015-09-10 05:31
@xion87 Feel free to fix them yourself, otherwise stop crying like a little bitch.

**Comment by teozfrank** [comment] 2015-09-10 22:40
@xion87 there is no need to be so impatient, I do this out of my spare time for free, other things in life take priority at the moment so it will take a while. Being demanding like that is really something that puts me off making these plugins, users of it take it for granted we will do as they please but im sorry but not thats not how it works. If you want it done when you want it, pay someone to do it or if you have some Java knowledge feel free to contribute, otherwise please keep those kind of comments to yourself and don't demand.

**Comment by gogobebe2** [comment] 2015-09-11 00:43
@teozfrank Keep up the good work mate, you're a good and passionate programmer. I'm a developer like you and I get extremely irritated when people become demanding like @xion87 .

**Comment by teozfrank** [comment] 2015-10-01 01:05
1. It doesnt take the food bars away it restores the players hunger to what it was before the duel started. This is intentional and not a bug. I will check for the hunger and health at the start of the duel.

2. this bug should be fixed in the latest release.

Closing this issue, if you find another bug please report it in a new issue. thanks.

**Closed by teozfrank** 2015-10-01 01:05 UTC
Labels: bug
