### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by illuminatithug69** [teozfrank/DuelMe#50] opened 2016-02-27 03:33 UTC
Doesnt teleport players after someone is killed

**Comment by illuminatithug69** [comment] 2016-02-27 03:51
it doesnt end the duel after a player dies WTF

**Comment by teozfrank** [comment] 2016-02-27 22:18
You prob have a plugin like combat log preventing the teleportation.

**Comment by illuminatithug69** [comment] 2016-02-28 22:32
No, I dont. It also glitches out when I reload the plugin and breaks everything and I need to delete the config folder.

**Comment by teozfrank** [comment] 2016-02-29 19:51
Any errors? What version of spigot are you running?

**Comment by illuminatithug69** [comment] 2016-03-01 23:38
1.8.8

**Comment by teozfrank** [comment] 2016-03-03 13:10
Dont reload the plugin, restart your server.

Could you list your plugins and provide me with a step by step guide into re-producing your issue please.

**Comment by teozfrank** [comment] 2016-03-22 15:33
Make an arena
    Get 2 people to join the game
    Let one win by killing the other player
    Wont teleport the other player out

Tested the first with minimum plugins required to run the plugin, cant reproduce. Player that dies is forced to respawn and player that wins is teleported back to origional location as intended.

And to make it all break

    Make an arena
    Get it all setup
    Do /dueladmin reload
    Watch all of your arenas disappear
    Plugin breaks so you need to restart the whole server then and then remake all of the arenas

Fixed in version 0.11.0 and above. There is actually no need to reload after creating arenas...

**Comment by teozfrank** [comment] 2016-05-10 19:40
Closed as no response made and issue was fixed in a newer version.

**Closed by teozfrank** 2016-05-10 19:40 UTC
Labels: bug
